spring.application.name=AskAi

spring.ai.openai.api-key=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